#!/bin/bash
# update parts

[[ -s $HOME/.nvm/nvm.sh ]] && . $HOME/.nvm/nvm.sh # This loads NVM
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"
cd workspace/

export PATH="$HOME/.parts/autoparts/bin:$PATH"
eval "$(parts init -)"

parts update

#startup from home
if [ -f /home/codio/startup.sh ]; then
  bash /home/codio/startup.sh
fi

#startup from project workspace
if [ -f /home/codio/workspace/startup.sh ]; then
  bash /home/codio/workspace/startup.sh
fi