#!/bin/bash

start ssh

# update parts
su codio -l -c "parts update"

#startup from home
if [ -f /home/codio/startup.sh ]; then
  su codio -l -c "bash /home/codio/startup.sh"
fi
#startup from project workspace
if [ -f /home/codio/workspace/startup.sh ]; then
  su codio -l -c "bash /home/codio/workspace/startup.sh"
fi
